version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb-data:

# This docker-compose.yml file will create a container named "mongo-server" using the latest MongoDB image, 
# and it will mount a volume from the host's /path/to/local/data to the container's /data/db directory. 
# This will allow you to persist the MongoDB data even if the container is deleted or recreated. 
# The container will also expose port 27017 to the host, 
# so that you can connect to the MongoDB server from the host using the standard MongoDB client or other MongoDB tools.
# Please make sure the directory on the host machine, you are mounting is present and also adjust the path as per your requirement.