apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: container-2
    image: redis:alpine
    ports:
    - containerPort: 6379


# This configuration creates a Pod named multi-container-pod with two containers: 
# container-1 running nginx image and 
# container-2 running redis image. 
# The containers are exposed on the specified ports, 80 and 6379 respectively.



