apiVersion: v1
kind: Service
metadata:
  name: orangehrm
  labels:
    app: orangehrm
spec:
  type: NodePort
  selector:
    app: orangehrm
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
