apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangehrm-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orangehrm-ui
  template:
    metadata:
      labels:
        app: orangehrm-ui
    spec:
      containers:
      - name: orangehrm-ui
        image: orangehrm/orangehrm:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: orangehrm-ui-service
spec:
  type: NodePort
  selector:
    app: orangehrm-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30090