version: '3'
services:
  studentfrontend:
    image: student-frontend:2.0
    ports:
      - 9200:80
  studentbackend:
    hostname: studentbackend
    image: student-backend:2.0
    ports:
      - 9300:9300
    depends_on:
      - db
  db:
    hostname: studentdatabase
    image: mongo
    ports:
      - 27017:27017