apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd       
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


# This is a Kubernetes deployment manifest written in YAML, defining a deployment named "nginx-deployment" 
# that runs 5 replicas of an nginx container. The deployment uses a RollingUpdate strategy and listens on port 80. 
# The selector specifies that the deployment should manage pods with the label "app: web", and the template
#  defines the metadata and spec of the pods to create.

# In addition to the previous information, this configuration has specified node affinity for the pods created by the deployment. 
# Node affinity is a property that allows you to constrain which nodes your pods can run on, based on labels on the nodes. 
# In this case, the nodeAffinity section specifies that the pods must be scheduled on a node with the label disktype set to ssd. 
# The requiredDuringSchedulingIgnoredDuringExecution section indicates that the node affinity rules must be met at scheduling time, 
# but are not enforced during pod execution.
