apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers



# The YAML configuration describes a DaemonSet in the "kube-system" namespace. 
# The DaemonSet has the name "fluentd-elasticsearch" and is labeled with "k8s-app: fluentd-logging". 
# The DaemonSet selector matches the nodes with label "name: fluentd-elasticsearch".

# The DaemonSet runs a container named "fluentd-elasticsearch" using the image "quay.io/fluentd_elasticsearch/fluentd:v2.5.2". 
# The container has resource constraints defined with limits on memory of 200Mi and requests for 100m of CPU and 200Mi of memory.

# The container runs with two volume mounts, "/var/log" and "/var/lib/docker/containers", which are hostPath volumes 
# that correspond to the host's log and docker containers directories. The termination grace period for the container is 30 seconds.

# The DaemonSet has a toleration defined to allow it to run on a node with the label "node-role.kubernetes.io/master" 
# with "effect: NoSchedule".



